### ISSUE TITLE
update

### ISSUE THREAD

**Issue by lolcat123456** [DiOnFire/gd-hackermode#1]
hi, if you dont mind me asking, and if you can, do you mind putting the latest version of the hack? just wondering

**Comment by DiOnFire** [comment]
ok

**Comment by lolcat123456** [comment]
> ok

thx!

**Comment by lolcat123456** [comment]
Hi! this probably makes me sound like an impatient brat, but do you mind giving an estimate on how long it will take to upload the v32.10 version of the hack? i understand you are probably busy and working on it, but i just would like an estimate

**Comment by DiOnFire** [comment]
Ok, i will update this today.

**Comment by lolcat123456** [comment]
Hi! It still doesnt seem that you have uploaded the 32.10 version of the hack, i really need to use the tasbot for a level showcase for my youtube channel, could you have uploaded it and i am not receiving or...
