### ISSUE TITLE
GD Doesn't open

### ISSUE THREAD

**Issue by Kyanoxia** [DiOnFire/gd-hackermode#4]
Hello.  After installing this... modded mod... GD doesn't open anymore.  This is probably because it is an older version.  If you instruct me on how to remove that ad at the beginning, I can maintain this repo for you.  I understand that it's not really being maintained anymore, as it hasn't been updated to 32 yet.

**Comment by DiOnFire** [comment]
just buy megahack

**Comment by Kyanoxia** [comment]
If I wanted Mega Hack I wouldn't have even been here in the first place.  If you're not going to update the repository, say it.  But I would still like to know what programs you used to remove the ad when it loads.  I am attempting to learn more about programming and modding anyhow, so it would be very helpful.  Thanks.
