### ISSUE TITLE
VIRUS

### ISSUE THREAD

**Issue by AManOnTheInternet** [DiOnFire/gd-hackermode#6]
THIS PROGRAM IS A VIRUS
![Issues · DiOnFire_gd-hackermode and 3 more pages - Personal - Microsoft​ Edge 12_28_2022 9_31_07 PM](https://user-images.githubusercontent.com/121592355/209899750-5ac7dd2d-1479-445e-9e01-1f1b288b801b.png)

**Comment by DiOnFire** [comment]
ну скачайте нормальную версию с официального сайта че вы докопались

**Comment by AManOnTheInternet** [comment]
i dont know where to get gd hackermode
